---

- hosts: localhost
  connection: local
  become: true

  tasks:
  # Install packages
  - name: install essential tools
    package:
      name:
        - wget
        - neofetch
        - htop
        - tmux
        - neovim
        - zsh
        - fzf
        - alacritty
        - firefox
        - qbittorrent

  - name: install developer tools
    package:
      name:
        - nmap
        - vscode
        - filezilla
        - aws-cli
        - docker
        - kubectl
        - minikube
        - terraform
  
  # - name: install spotify
  #   local_action: command sh scripts/install-spotify.sh
  
  # Yay package manager for linux
  - name: install yay package manager
    local_action: command sh scripts/install-yay.sh

  # Install spotify
  - name: install spotify
    local_action: command sh scripts/install-spotify.sh
    become: yes
    become_user: {{ lookup('env', 'NON_ROOT_USER') }}

  # Install postman REST API client
  - name: install postman rest api client
    local_action: command sh scripts/install-postman.sh
    become: yes
    become_user: {{ lookup('env', 'NON_ROOT_USER') }}

  # Set wallpaper
  # - name: copy wallpaper file
  #   copy:
  #     src: files/wallpaper.png
  #     dest: /usr/share/backgrounds/wallpaper.png
  #     owner: root
  #     group: root
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-uri"
  #     value: "'file:///usr/share/backgrounds/wallpaper.png'"
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-options"
  #     value: "'zoom'"
