---

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install essential tools
    package:
      name:
        - htop
        - tmux
        - neovim
        - zsh
        - fzf
        - alacritty
        - firefox
        - qbittorrent
  
  - name: install fun tools
    package:
      name:
        - neofetch
  
  - name: install developer tools
    package:
      name:
        - nmap
        - vscode
        - postman
        - filezilla
        - aws-cli
        - docker
        - kubectl
        - minikube
        - terraform
