---

- hosts: localhost
  connection: local
  become: true

  tasks:
  # Install packages
  - name: install essential tools
    package:
      name:
        - wget
        - neofetch
        - htop
        - tmux
        - neovim
        - zsh
        - fzf
        - alacritty
        - firefox
        - qbittorrent
        - openvpn
        - vlc

  - name: install developer tools
    package:
      name:
        - go
        - python-pip
        - python-setuptools
        - python-virtualenv
        - nmap
        - vscode
        - filezilla
        - aws-cli
        - docker
        - kubectl
        - minikube
        - terraform
  
  # Yay package manager for linux
  - name: install yay package manager
    local_action: command sh scripts/install-yay.sh

  # Install aur packages with yay
  # - name: install aur packages with yay
  #   become: yes
  #   become_user: robot
  #   shell: |
  #     #######################################
  #     # Install package with yay if it does not exists in a system.
  #     # Arguments:
  #     #   Command name.
  #     #   Package name.
  #     #######################################
  #     function yay_if_not_exists() {
  #       if ! command -v "$1" &> /dev/null
  #       then
  #         yay -a -Sy --noconfirm --cleanafter $2
  #       fi
  #     }

  #     # install spotify
  #     yay_if_not_exists "spotify" "spotify"

  #     # install postman
  #     yay_if_not_exists "postman" "postman-bin"

  #     # install slack
  #     yay_if_not_exists "slack" "slack-desktop"

  #     # install discord
  #     yay_if_not_exists "discord" "discord_arch_electron"

  #     # install telegram
  #     yay_if_not_exists "telegram" "telegram-desktop-bin"

  #     # install bitwarden
  #     yay_if_not_exists "bitwarden" "bitwarden-bin"

  #     # clean unneeded dependencies
  #     yay --clean --noconfirm

  # Install rust programming
  # - name: install rust programming language
  #   become: yes
  #   become_user: robot
  #   shell: |
  #     if ! command -v cargo &> /dev/null
  #     then
  #       curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
  #     fi
  
  # Install spacevim
  # - name: install spacevim
  #   become: yes
  #   become_user: robot
  #   shell: |
  #     curl -sLf https://spacevim.org/install.sh | bash

  # Setup zshrc and other configs
  - name: setup zshrc, oh-my-zsh and other configs
    become: yes
    become_user: robot
    shell: |
      # setup oh-my-zsh
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

      # create config folder if not exists
      if [ ! -d "~/.config" ]
      then
        mkdir $HOME/.config
      fi

      # create alacritty folder and setup config if not exists
      if [ ! -d "~/.config/alacritty" ]
      then
        mkdir ~/.config/alacritty
      fi
      wget https://raw.githubusercontent.com/the-robot/dots/master/terminals/alacritty/alacritty.yml -P ~/.config/alacritty

      # install tmux config
      wget https://raw.githubusercontent.com/the-robot/dots/master/terminals/tmux/.tmux.conf -P ~

      # install Vundle vim plugin manager
      if [! -d "~/.vim/bundle/Vundle.vim" ]
      then
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
      fi

      # install Ctrlp fzf vim plugin
      if [ ! -d "~/.vim/bundle/ctrlp.vim" ]
      then
        git clone https://github.com/ctrlpvim/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim
      fi

      # install neovim config
      if [ -d "~/.SpaceVim" ]
      then
        # install color
        wget https://raw.githubusercontent.com/the-robot/dots/master/vi/nvim/colors/monokai_pro.vim -P ~/.SpaceVim/colors

        # override config
        wget https://raw.githubusercontent.com/the-robot/dots/master/vi/nvim/init.vim ~/.SpaceVim
      fi

      # install spacevim config
      if [ ! -d "~/.SpaceVim.d" ]
      then
        mkdir ~/.SpaceVim.d
      fi
      wget https://raw.githubusercontent.com/the-robot/dots/master/vi/spacevim/init.toml -P ~/.SpaceVim.d

  # Set wallpaper
  # - name: copy wallpaper file
  #   copy:
  #     src: files/wallpaper.png
  #     dest: /usr/share/backgrounds/wallpaper.png
  #     owner: root
  #     group: root
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-uri"
  #     value: "'file:///usr/share/backgrounds/wallpaper.png'"
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-options"
  #     value: "'zoom'"
