---

- hosts: localhost
  connection: local
  become: true

  tasks:
  # Install packages
  - name: install essential tools
    package:
      name:
        - htop
        - tmux
        - neovim
        - zsh
        - fzf
        - alacritty
        - firefox
        - qbittorrent
  
  - name: install fun tools
    package:
      name:
        - neofetch
        - spotify
  
  - name: install developer tools
    package:
      name:
        - nmap
        - vscode
        - filezilla
        - aws-cli
        - docker
        - kubectl
        - minikube
        - terraform

  # Set wallpaper
  # - name: copy wallpaper file
  #   copy:
  #     src: files/wallpaper.png
  #     dest: /usr/share/backgrounds/wallpaper.png
  #     owner: root
  #     group: root
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-uri"
  #     value: "'file:///usr/share/backgrounds/wallpaper.png'"
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-options"
  #     value: "'zoom'"
