---

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install essential tools
    package:
      name:
        - htop
        - tmux
        - neovim
        - zsh
        - fzf
        - alacritty
        - firefox
        - qbittorrent
  
  - name: install fun tools
    package:
      name:
        - neofetch
  
  - name: install developer tools
    package:
      name:
        - nmap
        - vscode
        - filezilla
        - aws-cli
        - docker
        - kubectl
        - minikube
        - terraform

  # Install Postman with ansible
  - name: Inspect postman file
    stat: path=~/bin/Postman/Postman
    register: postman_file

  - name: Install postman
    when: not postman_file.stat.exists
    unarchive:
      remote_src: yes
      src: https://dl.pstmn.io/download/latest/linux64
      dest: ~/bin
