---

- hosts: localhost
  connection: local
  become: true

  tasks:
  # Install packages
  - name: install essential tools
    package:
      name:
        - wget
        - neofetch
        - htop
        - tmux
        - neovim
        - zsh
        - fzf
        - alacritty
        - firefox
        - qbittorrent
        - openvpn
        - vlc

  - name: install developer tools
    package:
      name:
        - python-pip
        - python-setuptools
        - python-virtualenv
        - nmap
        - vscode
        - filezilla
        - aws-cli
        - docker
        - kubectl
        - minikube
        - terraform
  
  # Yay package manager for linux
  - name: install yay package manager
    local_action: command sh scripts/install-yay.sh

  # Install packages with yay
  - name: install packages with yay
    become: yes
    become_user: robot
    shell: |
      #######################################
      # Install package with yay if it does not exists in a system.
      # Arguments:
      #   Command name.
      #   Package name.
      #######################################
      function yay_if_not_exists() {
        if ! command -v "$1" &> /dev/null
        then
          yay -a -Sy --noconfirm --cleanafter $2
        fi
      }

      # install spotify
      yay_if_not_exists "spotify" "spotify"

      # install postman
      yay_if_not_exists "postman" "postman-bin"

      # install slack
      yay_if_not_exists "slack" "slack-desktop"

      # install discord
      yay_if_not_exists "discord" "discord_arch_electron"

      # install telegram
      yay_if_not_exists "telegram" "telegram-desktop-bin"

      # install bitwarden
      yay_if_not_exists "bitwarden" "bitwarden-bin"

      # clean unneeded dependencies
      yay --clean --noconfirm

  # Install rust programming
  - name: install rust programming language
    become: yes
    become_user: robot
    shell: |
      if ! command -v cargo &> /dev/null
      then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      fi

  # Set wallpaper
  # - name: copy wallpaper file
  #   copy:
  #     src: files/wallpaper.png
  #     dest: /usr/share/backgrounds/wallpaper.png
  #     owner: root
  #     group: root
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-uri"
  #     value: "'file:///usr/share/backgrounds/wallpaper.png'"
  
  # - name: set wallpaper
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-options"
  #     value: "'zoom'"
